server:
 port: 8081
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://3.112.49.158:3306/shop?useUnicode=true&characterEncoding=utf-8
  username: sjmoon
  password: 1234
 devtools:
   livereload:
    enabled: true
 redis:
  host: 127.0.0.1
  port: 6379
 jpa:
  hibernate:
   ddl-auto: update
   #ddl-auto: create-drop
  properties:
   hibernate:
    show_sql: true
    format_sql: true
    use_sql_comments: true
 thymeleaf:
  prefix: classpath:templates/
  suffix: .html
  cache: false
  check-template-location: true
logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql: trace #sql 파라미터 확인
jwt:
 accessSecretKey: aG91Mjctc2ltcGxlLXNwcmluZy1ib290LWFwaS1qd3QK
 refreshSecretKey: bG91Kjctc2lasG23LXNwcmliZy138lGhLWFwaS1qd3QN
 accessTokenExpireTime: 300000
 refreshTokenExpireTime: 1209600000

root:
 path: C:/shop/ShopProject/src/main/resources/static/
# 이미지 업로드 경로 설정
image:
 product:
  path: img/product


